openapi: 3.0.0
info:
  title: eCommerce API - Productos
  description: API para gestionar productos en un eCommerce.
  version: "1.0.0"
servers:
  - url: 'http://localhost:8080/api'
    description: Servidor de desarrollo
paths:
  /products:
    get:
      summary: Obtener todos los productos
      tags:
        - Products
      responses:
        '200':
          description: Todos los productos fueron obtenidos satisfactoriamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor.
    post:
      summary: Crear un nuevo producto
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '201':
          description: Producto creado satisfactoriamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor.

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        title:
          type: string
          example: "aaaAA"
        description:
          type: string
          example: "Ex acerbitas saepe sumo verbera tabgo tantum atqui defero tollo."
        category:
          type: string
          example: "Bebes"
        price:
          type: number
          example: 942
        code:
          type: string
          example: "mJhUcl"
        stock:
          type: number
          example: 1
        thumbnail:
          type: string
          example: "https://picsum.photos/seed/picsum/640/480"
      required:
        - title
        - description
        - category
        - price
        - code
        - stock

    ProductInput:
      type: object
      properties:
        title:
          type: string
          example: "Nuevo Producto"
        description:
          type: string
          example: "Descripción detallada del nuevo producto."
        category:
          type: string
          example: "Electrónica"
        price:
          type: number
          example: 299.99
        code:
          type: string
          example: "XYZ123"
        stock:
          type: number
          example: 50
        thumbnail:
          type: string
          example: "https://picsum.photos/id/237/200/300"
      required:
        - title
        - description
        - category
        - price
        - code
        - stock
